name: Build

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets. REPO_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets. REPO_TOKEN }}

      - name: Cache Docker layers 
        uses: actions/cache@v4.2.3
        with:
            path: /tmp/.docker-cache
            key: docker-cache-${{ runner.os }}-${{ github.ref_name }}
            restore-keys: |
              docker-cache-${{ runner.os }}-
  
      - name: Build and push simulation image
        run: |
              ./scripts/build_sim.sh 

