name: Continuous Integration
on:
  repository_dispatch:
    types: [run-tagged-workflow]

  push:
    tags:
      - 'v*'
      
  workflow_dispatch:

jobs:
  build:
    name: Build Docker image
    uses: ./.github/workflows/build.yml
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  sitl:
    name: Software in the Loop
    uses: ./.github/workflows/sitl.yml
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    needs: build
