# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025, Iftach Naftaly <iftahnaf@gmail.com>
name: Continuous Integration
on:
  repository_dispatch:
    types: [run-tagged-workflow]

  push:
    tags:
      - 'v*'
      
  workflow_dispatch:

jobs:
  build:
    if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
    name: Build Docker image
    uses: ./.github/workflows/build.yml
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  wait-for-build:
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
      - run: echo "Proceeding after optional build step"

  sitl:
    name: Software in the Loop
    uses: ./.github/workflows/sitl.yml
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
    needs: [wait-for-build]

  data:
    name: Run Bag Analysis
    uses: ./.github/workflows/data.yml
    needs: sitl
    with:
      s3_path: ${{ needs.sitl.outputs.s3_path }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

  release:
    name: Trigger GitHub Release
    if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
    uses: ./.github/workflows/release.yml
    needs: data
    with:
      tag: ${{ github.ref_name }}
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
