# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025, Iftach Naftaly <iftahnaf@gmail.com>
name: Continuous Integration
on:
  repository_dispatch:
    types: [run-tagged-workflow]

  push:
    tags:
      - 'v*'
      
  workflow_dispatch:

jobs:
  build:
    name: Build Docker image
    uses: ./.github/workflows/build.yml
    if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

  wait-for-build:
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
      - run: echo "Proceeding after optional build step"

  sitl:
    name: Software in the Loop
    uses: ./.github/workflows/sitl.yml
    needs: [wait-for-build]
    if: always()
    with:
      radius: 1.0
      altitude: 30.0
      angular_velocity: 0.5
      duration: 120.0
      offboard_time_s: 30.0
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}


  data:
    name: Run Bag Analysis
    uses: ./.github/workflows/data.yml
    needs: sitl
    if: always()
    with:
      bag_path: ${{ needs.sitl.outputs.bag_path }}
      bag_file_name: ${{ needs.sitl.outputs.bag_file_name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

  release:
    name: Trigger GitHub Release
    uses: ./.github/workflows/release.yml
    needs: data
    if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
    with:
      tag: ${{ github.ref_name }}
    secrets:
      REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
