# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025, Iftach Naftaly <iftahnaf@gmail.com>
name: Analyze Bag Data

on:
  workflow_call:
    inputs:
      bag_path:
        required: true
        type: string
      bag_file_name:
        required: true
        type: string
      multi_run:
        type: boolean
        default: false
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      REPO_TOKEN:
        required: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.REPO_TOKEN }}

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
          arch: amd64

      - name: Download latest bag file from S3
        run: |
          mkdir -p data
          echo "Downloading bag files from S3..."
          if [ "${{ inputs.multi_run }}" = "true" ]; then
            aws s3 cp "${{ inputs.bag_path }}" ./data --recursive
          else
            aws s3 cp "${{ inputs.bag_path }}${{ inputs.bag_file_name }}" ./data/${{ inputs.bag_file_name }} --recursive
          fi
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install rosbags matplotlib

      - name: Run single bag analysis
        if: ${{ inputs.multi_run == false }}
        run: |
          python3 ./scripts/report_single.py ./data/${{ inputs.bag_file_name }} --commit_id ${{ github.sha }} --author ${{ github.actor }}
          echo "Analysis complete."
      - name: Run Multi bag analysis
        if: ${{ inputs.multi_run == true }}
        run: |
          folder_name=$(basename "${{ inputs.bag_path }}")
          python3 ./scripts/report_multi.py ./data/$folder_name --commit_id ${{ github.sha }} --author ${{ github.actor }}
          echo "Analysis complete."

      - name: Upload to Artifact
        uses: actions/upload-artifact@v4
        with:
          name: uploaded-artifact
          path: results/*.pdf
          if-no-files-found: error
