# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2025, Iftach Naftaly <iftahnaf@gmail.com>
name: Analyze Bag Data

on:
  workflow_call:
    inputs:
      s3_path:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      REPO_TOKEN:
        required: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}

      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
          arch: amd64

      - name: Download bag file from S3
        run: |
          mkdir -p data
          echo "Downloading bag file from S3..."
          echo "S3 path: ${{ inputs.s3_path }}"
          aws s3 cp "${{ inputs.s3_path }}" ./data/ --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Run bag analysis
        run: |
          python3 ./scripts/bag_analysis.py ./data
          echo "Analysis complete."

      - name: Commit and push analysis result
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add '**/*.md'
          git commit -m "docs: add bag analysis report from ${{ inputs.s3_path }}"
          git push
