name: Create Release

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      REPO_TOKEN:
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download topic report
        run: |
          mkdir -p dist
          echo "Fetching topic_report.md from artifacts..."

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
